    echo "找到 Image 文件: $image_path"
                cp "$image_path" "$target1"
                cp "$image_path" "$target2"
              else
                echo "在所有目录中未找到 Image 文件，构建可能失败"
              fi
            fi
          fi
         
         
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: AnyKernel3_KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
         path: ./AnyKernel3/*

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image_KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
         path: kernel_workspace/kernel
